source "https://api.berkshelf.com"

metadata

cookbook 'heka', git: 'git://github.com/augieschwer/chef-cookbook-heka.git'
cookbook 'zookeeper', git: 'git://github.com/SimpleFinance/chef-zookeeper.git'
cookbook 'kafka', git: 'git://github.com/mthssdrbrg/kafka-cookbook.git'
